ll = ['ip', 'conv7', 'conv5', 'conv3', 'conv4', 'avg-pool', 'max-pool', 'max-pool', 'fc', 'conv3', 'max-pool', 'fc', 'softmax', 'softmax', 'op']
lu = [1, 16, 32, 16, 16, 1, 1, 1, 16, 16, 1, 16, 0, 0, 0]
path = [[], [0], [1], [1], [1], [2], [3], [4], [5], [7], [9], [6,10], [8], [8,11], [12,13]]
