ll = ['ip', 'res5', 'conv3', 'res3', 'avg-pool', 'avg-pool', 'conv3', 'avg-pool', 'fc', 'fc', 'softmax', 'op']
lu = [1, 16, 9, 9, 1, 1, 32, 1, 20, 18, 0, 0]
path = [[], [0], [1], [1], [1], [1], [2,3], [6], [4,5,7], [8], [9], [10]]
