ll = ['ip', 'conv3', 'conv3', 'conv3', 'avg-pool', 'max-pool', 'fc', 'fc', 'fc', 'softmax', 'softmax', 'softmax', 'op']
lu = [1, 18, 18, 32, 1, 1, 14, 14, 16, 0, 0, 0, 0]
path = [[], [0], [1], [2], [2], [3], [4,5], [5], [5], [6], [7], [8], [9,10,11]]
