ll = ['ip', 'conv3', 'conv3', 'max-pool', 'conv3', 'conv3', 'max-pool', 'conv3', 'conv3', 'conv3', 'avg-pool', 'conv3', 'conv3', 'max-pool', 'conv3', 'conv3', 'max-pool', 'fc', 'fc', 'fc', 'softmax', 'op']
lu = [1, 56, 56, 1, 112, 128, 1, 128, 128, 128, 1, 256, 256, 1, 576, 512, 1, 128, 256, 512, 0, 0]
path = [[], [0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20]]
