ll = ['ip', 'conv3', 'conv3', 'conv3', 'conv3', 'max-pool', 'conv3', 'max-pool', 'avg-pool', 'max-pool', 'max-pool', 'fc', 'max-pool', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'softmax', 'softmax', 'softmax', 'softmax', 'op']
lu = [1, 16, 18, 16, 36, 1, 36, 1, 1, 1, 1, 28, 1, 28, 28, 28, 28, 32, 32, 28, 25, 28, 0, 0, 0, 0, 0]
path = [[], [0], [0], [1], [1], [1], [2], [3], [3], [4], [4], [5], [6], [5,7,8], [9], [10], [12], [13], [14], [14], [16], [11,17], [15,18,19], [19], [20], [21], [22,23,24,25]]

