ll = ['ip', 'conv3', 'conv3', 'conv3', 'conv3', 'avg-pool', 'conv3', 'max-pool', 'avg-pool', 'max-pool', 'fc', 'max-pool', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'softmax', 'softmax', 'softmax', 'softmax', 'op']
lu = [1, 18, 20, 18, 41, 1, 41, 1, 1, 1, 32, 1, 32, 25, 25, 25, 19, 22, 19, 22, 0, 0, 0, 0, 0]
path = [[], [0], [0], [1], [1], [1], [2], [3], [3], [4], [5], [6], [5,7,8], [9], [11], [12], [13], [13], [14], [10,15], [16,17], [17], [18], [19], [20,21,22,23]]
