ll = ['ip', 'conv3', 'conv3', 'res5', 'conv3', 'avg-pool', 'conv3', 'conv5', 'res3', 'conv3', 'avg-pool', 'conv3', 'avg-pool', 'avg-pool', 'avg-pool', 'avg-pool', 'fc', 'fc', 'fc', 'fc', 'fc', 'fc', 'softmax', 'op']
lu = [1, 16, 16, 16, 16, 1, 16, 32, 32, 32, 1, 32, 1, 1, 1, 1, 32, 36, 36, 36, 36, 36, 0, 0]
path = [[], [0], [0], [1], [1], [1], [2], [3], [3], [4], [6], [7], [8], [9], [11], [11], [10, 13], [14], [5,12,15], [17], [17,18], [19],[20,21],[22]]
